### Create new Author
POST http://localhost:8080/api/v1/authors
Content-Type: application/json
Authorization: Bearer <token>

{
  "firstName": "<author_first_name>",
  "lastName": "<author_last_name>"
}

### Update Author by ID
PATCH http://localhost:8080/api/v1/authors/<author_id>
Content-Type: application/json
Authorization: Bearer <token>

{
  "firstName": "<new_first_name>",
  "lastName": "<new_last_name>"
}

### Get all Authors
GET http://localhost:8080/api/v1/authors
Content-Type: application/json
Authorization: Bearer <token>

### Get Author by ID
GET http://localhost:8080/api/v1/authors/<author_id>
Content-Type: application/json
Authorization: Bearer <token>

### Delete Author by ID
DELETE http://localhost:8080/api/v1/authors/<author_id>
Content-Type: application/json
Authorization: Bearer <token>