### Create new book
POST http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "<book_title>",
  "authorId": 0,
  "genreId": 0,
  "count": 0
}

### Update book by ID
PATCH http://localhost:8080/api/v1/books/<book_id>
Content-Type: application/json
Authorization: Bearer <token>

{
  "title": "<new_book_title>",
  "authorId": 0,
  "genreId": 0,
  "count": 0
}

### Get all books
GET http://localhost:8080/api/v1/books
Content-Type: application/json
Authorization: Bearer <token>

### Get book by ID
GET http://localhost:8080/api/v1/books/<book_id>
Content-Type: application/json
Authorization: Bearer <token>

### Search books by title and author (both first and last name or one)
GET http://localhost:8080/api/v1/books/search?title=<book_title>&author=<author_name>
Content-Type: application/json
Authorization: Bearer <token>

### Delete book by ID
DELETE http://localhost:8080/api/v1/books/<book_id>
Content-Type: application/json
Authorization: Bearer <token>
