### Create new Librarian
POST http://localhost:8080/api/v1/librarians
Content-Type: application/json
Authorization: Bearer <token>

{
  "username": "<librarian_username>",
  "password": "<librarian_password>",
  "workTime": "<work_time_type>"
}

### Get All Librarians
GET http://localhost:8080/api/v1/librarians
Content-Type: application/json
Authorization: Bearer <token>

### Get Librarian by ID
GET http://localhost:8080/api/v1/librarians/<librarian_id>
Content-Type: application/json
Authorization: Bearer <token>

### Update librarian username and work time(admin)
PATCH http://localhost:8080/api/v1/librarians/admin/me/<librarian_ID>
Content-Type: application/json
Authorization: Bearer <token>

{
  "username": "dono" ,
  "workTime": "EVENING"
}


### Change librarian password (if librarian id is provided we check for admin)
PATCH http://localhost:8080/api/v1/librarians/me/password
Content-Type: application/json
Authorization: Bearer <token>

{
  "oldPassword": "2",
  "newPassword": "3",
  "confirmPassword": "3"
}

### Delete librarian by ID (admin)
DELETE http://localhost:8080/api/v1/librarians/admin/<librarian_ID>
Content-Type: application/json
Authorization: Bearer <token>

